security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_INVITADO:    ROLE_USER
        ROLE_REGISTRADO:  ROLE_INVITADO
        ROLE_INTERVENTOR: ROLE_REGISTRADO
        ROLE_ADMIN:       ROLE_INTERVENTOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios, role: ROLE_INTERVENTOR }
        - { path: ^/archivos/eliminar, role: ROLE_INTERVENTOR }
        - { path: ^/archivos, role: ROLE_REGISTRADO }
