# app/config/security.yml
security:
    encoders:
       Aac\AacBundle\Entity\Usuarios:
         id: My_Hash

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMINISTRADOR, ROLE_ALLOWED_TO_SWITCH ]
    providers:
        main:
            entity: { class: AacBundle:Usuarios, property: usuario }
    firewalls:
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            form_login: ~        
          
